package chat

// The route, run through the real program.
//
// A golden renders one surface in-process and proves what it looks like. This
// file asks the other question a golden cannot: does the key get there. It
// starts a real tea.Program over the session model, sends the keys a reader
// sends, lets the scripted provider's stream arrive on the runtime's own
// goroutines, and reads the frame the program ends on.
//
// On program-level goldens: there are none here, and none are wanted.
// teatest.RequireEqualOutput would capture the accumulated byte stream of
// every frame the renderer emitted — cursor moves, partial repaints and all —
// which is a record of how the runtime got to a screen rather than of the
// screen. internal/ui/golden already owns the screen, at four widths in two
// palettes, from a model built directly; a second golden of the same surface
// taken through the runtime would fail on a bubbletea repaint change that
// altered nothing anyone sees, and would have to be regenerated by whoever
// hit it, which is how a golden stops being read. So the assertions here name
// the text the route had to carry and nothing else, and the render stays the
// goldens' question.

import (
	"context"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"
	"testing"
	"time"

	tea "charm.land/bubbletea/v2"
	"github.com/charmbracelet/x/exp/teatest/v2"
	"github.com/rfizzle/shhh/internal/config"
	"github.com/rfizzle/shhh/internal/persona"
	"github.com/rfizzle/shhh/internal/provider"
	"github.com/rfizzle/shhh/internal/ui/keys"
)

// programTurn is one answer the provider gives, in the order the turns are
// listed: some text, some tool calls, or both.
type programTurn struct {
	text  string
	calls []provider.ToolCall
	// hold, when set, keeps this turn's events off the channel until it is
	// closed. It is what makes a card's arrival orderable against the keys
	// the test is sending: a decision that lands while the draft holds a
	// sentence arrives ungated, and a test that cannot say when it lands
	// cannot say which of the two branches it is testing (interrupt.go).
	hold chan struct{}
	// usage, when set, is what the turn's closing event reports the request
	// cost, the way an endpoint's final chunk does.
	usage *provider.Usage
}

// programProvider is a provider.Provider that answers each request with the
// next scripted turn, repeating the last one once they run out — the same
// contract the driven scenes' fake endpoint has.
type programProvider struct {
	mu    sync.Mutex
	turns []programTurn
	next  int
	// asked is the last message of every request, in order: what the
	// session put in front of the model at each round boundary.
	asked []provider.Message
}

func (p *programProvider) Name() string { return "scripted" }

func (p *programProvider) StreamCompletion(ctx context.Context, msgs []provider.Message, _ provider.CompletionOpts) (<-chan provider.StreamEvent, error) {
	p.mu.Lock()
	if len(msgs) > 0 {
		p.asked = append(p.asked, msgs[len(msgs)-1])
	}
	turn := p.turns[min(p.next, len(p.turns)-1)]
	p.next++
	p.mu.Unlock()

	ch := make(chan provider.StreamEvent, 2)
	go func() {
		defer close(ch)
		if turn.hold != nil {
			select {
			case <-turn.hold:
			case <-ctx.Done():
				return
			}
		}
		if turn.text != "" {
			ch <- provider.StreamEvent{Token: turn.text}
		}
		ch <- provider.StreamEvent{ToolCalls: turn.calls, Usage: turn.usage, Done: true}
	}()
	return ch, nil
}

// streamOf is the adapter every host writes around its provider to hand the
// session a StreamFunc: a cancellable request per turn.
func streamOf(p provider.Provider) StreamFunc {
	return func(msgs []provider.Message, choice string) (<-chan provider.StreamEvent, context.CancelFunc, error) {
		ctx, cancel := context.WithCancel(context.Background())
		events, err := p.StreamCompletion(ctx, msgs, provider.CompletionOpts{ToolChoice: choice})
		if err != nil {
			cancel()
			return nil, nil, err
		}
		return events, cancel, nil
	}
}

// runProgram starts the session under a real tea.Program at a stated size.
// The size is sent as the WindowSizeMsg the program's first frame needs; the
// model draws nothing until it has one (model_test.go).
func runProgram(t *testing.T, m Model) *program {
	t.Helper()
	return runProgramAt(t, m, 120, 40)
}

// runProgramAt is runProgram at a terminal of a stated size, for the routes
// whose surface is only drawn past a width.
func runProgramAt(t *testing.T, m Model, cols, rows int) *program {
	t.Helper()
	p := &program{frame: new(atomic.Pointer[string])}
	p.TestModel = teatest.NewTestModel(t, watched{Model: m, frame: p.frame}, teatest.WithInitialTermSize(cols, rows))
	t.Cleanup(func() { _ = p.Quit() })
	return p
}

// program is the running session and the last frame it drew.
type program struct {
	*teatest.TestModel
	frame *atomic.Pointer[string]
}

// watched is the session with its View noted as the runtime draws it, so a
// test waits on the screen and not on the byte stream the renderer wrote.
// The stream is the terminal's repaints — a row that changed by one word is
// written as that word, a run of spaces as a cursor move — so a phrase can be
// on the screen and never contiguous in the stream.
type watched struct {
	Model
	frame *atomic.Pointer[string]
}

func (w watched) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	next, cmd := w.Model.Update(msg)
	if m, ok := next.(Model); ok {
		w.Model = m
		return w, cmd
	}
	return next, cmd
}

func (w watched) View() tea.View {
	v := w.Model.View()
	s := stripANSI(v.Content)
	w.frame.Store(&s)
	return v
}

// waitForText blocks until the program has drawn s, and says what it was
// waiting for when it never does. The wait is on the frames rather than on a
// clock: a sleep is a guess about a machine's speed, and this suite runs on
// three of them. It reads the last frame the runtime drew, so a phrase the
// frame before already carried matches at once: wait for what the step being
// waited on puts there.
func waitForText(t *testing.T, tm *program, s string) {
	t.Helper()
	deadline := time.Now().Add(10 * time.Second)
	for time.Now().Before(deadline) {
		if f := tm.frame.Load(); f != nil && strings.Contains(*f, s) {
			return
		}
		time.Sleep(10 * time.Millisecond)
	}
	last := ""
	if f := tm.frame.Load(); f != nil {
		last = *f
	}
	t.Fatalf("the program never drew %q; the last frame was:\n%s", s, last)
}

// finalFrame quits the program and returns the screen it ended on, stripped
// of colour. It is the model's own last View rather than the accumulated
// output, because the output is every frame the renderer emitted and the
// question here is what the last one said.
func finalFrame(t *testing.T, tm *program) string {
	t.Helper()
	if err := tm.Quit(); err != nil {
		t.Fatalf("quitting the program: %v", err)
	}
	final, ok := tm.FinalModel(t, teatest.WithFinalTimeout(10*time.Second)).(watched)
	if !ok {
		t.Fatal("the program did not end on the chat model")
	}
	return stripANSI(final.View().Content)
}

// The keys a reader presses, spelled once: send, the handover that gives a
// waiting decision the keyboard, and the card's allow.
var (
	programEnter    = tea.KeyPressMsg{Code: tea.KeyEnter}
	programHandover = tea.KeyPressMsg{Code: tea.KeySpace, Mod: tea.ModCtrl}
	programAlias    = tea.KeyPressMsg{Code: 'y', Mod: tea.ModCtrl}
	programAllow    = tea.KeyPressMsg{Code: 'y', Text: "y"}
)

// draftSentence is the half-typed line the card lands on top of.
const draftSentence = "half a thought"

// A typed line reaches the provider and the reply reaches the screen: the
// whole round trip through the runtime, with nothing driving Update by hand.
func TestProgram_ATypedLineFetchesAReplyOntoTheFrame(t *testing.T) {
	p := &programProvider{turns: []programTurn{{text: "the scripted answer"}}}
	tm := runProgram(t, New([]provider.Message{{Role: provider.RoleSystem, Content: "sys"}}, streamOf(p)))

	tm.Type("say something")
	tm.Send(programEnter)
	waitForText(t, tm, "the scripted answer")

	if frame := finalFrame(t, tm); !strings.Contains(frame, "the scripted answer") {
		t.Fatalf("the reply is not on the final frame:\n%s", frame)
	}
}

// heldCommandProgram is the fixture the two card tests share: a session whose
// next turn asks to run a command, held until the test says so, with a
// sentence in the draft when it lands. The sentence is what puts the card in
// its arrival state — on screen, keys not live, the draft still holding the
// keyboard — which is the state both keys below are asked about.
func heldCommandProgram(t *testing.T, ran *[]string) *program {
	t.Helper()
	hold := make(chan struct{})
	// Released once, whichever way the test leaves: a fixture that fails
	// before the release would otherwise park the provider's goroutine on a
	// channel nothing will ever close.
	release := sync.OnceFunc(func() { close(hold) })
	t.Cleanup(release)
	p := &programProvider{turns: []programTurn{
		{hold: hold, calls: []provider.ToolCall{
			{ID: "call_1", Name: "execute_command", Arguments: `{"command":"echo hi"}`},
		}},
		{text: "and that is done"},
	}}
	m := New([]provider.Message{{Role: provider.RoleSystem, Content: "sys"}}, streamOf(p)).
		WithRunner(legacyRunner(func(_ context.Context, cmd string) (string, int) {
			*ran = append(*ran, cmd)
			return "hi", 0
		}))
	tm := runProgram(t, m)

	tm.Type("run it")
	tm.Send(programEnter)
	// Sent after the enter and therefore handled after it, so a frame
	// carrying this sentence is a frame where the turn is away and the draft
	// is not empty. It arrives as a paste, one message, so the first frame
	// that carries it carries all of it.
	tm.Send(tea.PasteMsg{Content: draftSentence})
	waitForText(t, tm, draftSentence)

	release()
	waitForText(t, tm, "Approve command")
	return tm
}

// The approval card is reachable by key, not only by render: the call
// arrives, the handover gives the card the keyboard, and [y] runs the
// command and puts its row in the transcript.
func TestProgram_TheApprovalCardsKeysRunTheCommand(t *testing.T) {
	var ran []string
	tm := heldCommandProgram(t, &ran)

	tm.Send(programHandover)
	tm.Send(programAllow)
	waitForText(t, tm, "and that is done")

	frame := finalFrame(t, tm)
	if len(ran) != 1 || ran[0] != "echo hi" {
		t.Fatalf("the allowed command did not reach the runner, got %v\n%s", ran, frame)
	}
	// The row the run left, read off the frame rather than off the model: the
	// act, what it was aimed at, and how it went.
	for _, want := range []string{"$ ran", "echo hi", "ok ·"} {
		if !strings.Contains(frame, want) {
			t.Fatalf("the command's row is not in the transcript, no %q:\n%s", want, frame)
		}
	}
	if strings.Contains(frame, "$ echo hi") {
		t.Fatalf("the answered card is still on the screen:\n%s", frame)
	}
	// Answering hands the keyboard back at the character it was taken from.
	if !strings.Contains(frame, draftSentence) {
		t.Fatalf("the interrupted sentence did not come back:\n%s", frame)
	}
}

// The other half of invariant 5, asked of the whole program: while the draft
// holds the keyboard, the card's own answer key is a letter. It goes into the
// sentence, nothing runs, and the card is still waiting on the final frame
// (docs/interface/principles.md#a-key-is-inert-until-its-surface-holds-the-keyboard).
func TestProgram_ACardsKeyIsInertUntilTheHandover(t *testing.T) {
	var ran []string
	tm := heldCommandProgram(t, &ran)

	tm.Send(programAllow)
	// No wait: the quit inside finalFrame goes down the same queue as the
	// key, so the model it ends on is the model that has answered it.
	frame := finalFrame(t, tm)
	if !strings.Contains(frame, draftSentence+"y") {
		t.Fatalf("the card's key did not go into the sentence it landed on:\n%s", frame)
	}
	if len(ran) != 0 {
		t.Fatalf("a key the card does not hold ran the command: %v\n%s", ran, frame)
	}
	if !strings.Contains(frame, "$ echo hi") {
		t.Fatalf("the card left the screen without being answered:\n%s", frame)
	}
	// And it says so in words rather than leaving the reader to infer it
	// from a key row nothing painted: the card draws the one key that is
	// live and says where the rest of them are going (invariant 1).
	if !strings.Contains(frame, "other keys type into the draft") {
		t.Fatalf("the card does not say where the keystrokes are going:\n%s", frame)
	}
	if strings.Contains(frame, "[y]") {
		t.Fatalf("the card drew a key the draft would answer:\n%s", frame)
	}
}

// The handover's cover, through the whole program. macOS takes ctrl+space for
// its input-source switcher before the terminal sees it, so the card names
// ctrl+y beside it, and ctrl+y has to do everything the first chord does: a
// bare y typed before it is still a letter of the sentence, the alias gives
// the card the keyboard, the card's y then runs the command, and the draft
// comes back holding every character typed into it
// (docs/interface/principles.md#a-key-is-inert-until-its-surface-holds-the-keyboard).
func TestProgram_TheHandoversCoverAnswersFromAHalfTypedLine(t *testing.T) {
	var ran []string
	tm := heldCommandProgram(t, &ran)
	waitForText(t, tm, keys.Bracket(keys.Draft.Answer)+" answer it")

	tm.Send(programAllow)
	waitForText(t, tm, draftSentence+"y")
	if len(ran) != 0 {
		t.Fatalf("a bare y beside a live draft ran the command: %v", ran)
	}

	tm.Send(programAlias)
	tm.Send(programAllow)
	waitForText(t, tm, "and that is done")

	frame := finalFrame(t, tm)
	if len(ran) != 1 || ran[0] != "echo hi" {
		t.Fatalf("the command did not run after the alias handed the card the keyboard, got %v\n%s", ran, frame)
	}
	if !strings.Contains(frame, draftSentence+"y") {
		t.Fatalf("the draft did not keep what was typed into it:\n%s", frame)
	}
}

// The drafter's draft step is reached and revised by key through the whole
// program: the draft arrives from the drafting turn on the runtime's own
// goroutine, the pointer walks to a section, a note is sent about it, and the
// answer lands on that section alone
// (docs/interface/surfaces.md#the-profile-drafter).
func TestProgram_TheDraftIsRevisedOneSectionAtATime(t *testing.T) {
	first := &persona.Draft{Name: "test-writer", Description: "adds tests", Permissions: []string{"write"},
		Sections: &persona.Sections{Purpose: "Add tests.", Scope: "One package.", Restrictions: "Never delete a test.",
			Method: "Read, then write.", Report: "The cases added."}}
	answer := &persona.Draft{Name: "renamed", Description: "something else",
		Sections: &persona.Sections{Purpose: "NEW purpose.", Method: "Run go vet after each file."}}
	var mu sync.Mutex
	var asked []persona.Request
	m := New([]provider.Message{{Role: provider.RoleSystem, Content: "sys"}}, streamOf(&programProvider{turns: []programTurn{{text: "unused"}}})).
		WithPersonas(Personas{
			Kind:    persona.KindCode,
			Enabled: true,
			Draft: func(_ context.Context, req persona.Request) persona.Outcome {
				mu.Lock()
				defer mu.Unlock()
				asked = append(asked, req)
				if req.Section == "" {
					return persona.Outcome{Draft: first}
				}
				return persona.Outcome{Draft: answer}
			},
			Save: func(persona.Scope, persona.Draft, bool) (string, error) {
				t.Error("nothing is written before the card's save row is taken")
				return "", nil
			},
		})
	tm := runProgramAt(t, m, 120, 50)

	tm.Type("/agents new a test writer")
	tm.Send(programEnter)
	waitForText(t, tm, "Keep test-writer?")
	for range 3 {
		tm.Send(tea.KeyPressMsg{Code: tea.KeyDown})
	}
	tm.Send(programEnter)
	waitForText(t, tm, "what to change in Method")
	tm.Type("run go vet")
	tm.Send(programEnter)
	waitForText(t, tm, "Method · refined once")

	frame := finalFrame(t, tm)
	for _, want := range []string{"Run go vet after each file.", "Add tests.", "[esc] take back its last revision"} {
		if !strings.Contains(frame, want) {
			t.Fatalf("the revised draft lacks %q:\n%s", want, frame)
		}
	}
	if strings.Contains(frame, "NEW purpose.") {
		t.Fatalf("a note about Method rewrote Purpose:\n%s", frame)
	}
	mu.Lock()
	defer mu.Unlock()
	if len(asked) != 2 || asked[1].Section != "Method" || asked[1].Feedback != "run go vet" {
		t.Fatalf("requests = %+v", asked)
	}
}

// An older profile is migrated from the manager through the whole program,
// over real files: m moves it into the sections, the card replaces its file,
// the save registers it again the way an edited role is, and its row loses
// the mark. A save the loader would refuse is refused on the card in the
// loader's words, with the file untouched
// (docs/capabilities/subagents.md#an-older-profile-is-moved-into-sections-not-rewritten).
func TestProgram_AnOlderProfileIsMigratedFromTheManager(t *testing.T) {
	dir := t.TempDir()
	critic := filepath.Join(dir, "critic.toml")
	terse := filepath.Join(dir, "terse.toml")
	const terseFile = "description = \"says little\"\nprompt_mode = \"replace\"\nprompt = \"Be terse.\"\n"
	if err := os.WriteFile(critic, []byte(criticFile), 0o600); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(terse, []byte(terseFile), 0o600); err != nil {
		t.Fatal(err)
	}
	var mu sync.Mutex
	var reloaded []string
	roles := func() []SpawnableRole {
		var out []SpawnableRole
		for _, path := range []string{critic, terse} {
			def, err := config.LoadAgentFile(path)
			if err != nil {
				t.Error(err)
				continue
			}
			out = append(out, SpawnableRole{Name: def.Name, Description: def.Description, Scope: "project", Path: path, Older: !def.Current()})
		}
		return out
	}
	reload := func(path string) error {
		mu.Lock()
		defer mu.Unlock()
		reloaded = append(reloaded, path)
		_, err := config.LoadAgentFile(path)
		return err
	}
	m := New([]provider.Message{{Role: provider.RoleSystem, Content: "sys"}}, streamOf(&programProvider{turns: []programTurn{{text: "unused"}}})).
		WithPersonas(Personas{
			Kind:    persona.KindCode,
			Enabled: true,
			Roles:   roles,
			Reload:  reload,
			Open:    persona.Open,
			Draft: func(_ context.Context, req persona.Request) persona.Outcome {
				if req.Source != nil {
					return persona.Outcome{Draft: criticMigrated(&persona.Source{Def: *req.Source})}
				}
				// The gap the migration left, filled by a note on its section.
				filled := *req.Current
				filled.SetSection(config.SectionMethod, "Read the diff, then the files it touches.")
				return persona.Outcome{Draft: &filled}
			},
			SaveOpened: func(src *persona.Source, d persona.Draft) (string, error) {
				path, err := persona.SaveOpened(src, d)
				if err != nil {
					return path, err
				}
				return path, reload(path)
			},
		})
	tm := runProgramAt(t, m, 130, 60)

	tm.Type("/agents")
	tm.Send(programEnter)
	waitForText(t, tm, "◆ older shape")
	tm.Send(tea.KeyPressMsg{Code: tea.KeyDown})
	tm.Send(tea.KeyPressMsg{Code: 'm', Text: "m"})
	waitForText(t, tm, "Purpose · migrated")
	for range 3 {
		tm.Send(tea.KeyPressMsg{Code: tea.KeyDown})
	}
	tm.Send(programEnter)
	waitForText(t, tm, "what to change in Method")
	tm.Type("say how it reads")
	tm.Send(programEnter)
	waitForText(t, tm, "Method · refined once")
	tm.Send(tea.KeyPressMsg{Code: tea.KeyTab})
	tm.Send(programEnter)
	waitForText(t, tm, "Saved critic")
	tm.Type("/agents")
	tm.Send(programEnter)
	waitForText(t, tm, "says little")

	// The second older role: its Purpose cleared leaves a replace-mode
	// profile with no prompt, which the loader refuses.
	tm.Send(tea.KeyPressMsg{Code: tea.KeyDown})
	tm.Send(tea.KeyPressMsg{Code: tea.KeyDown})
	tm.Send(programEnter)
	waitForText(t, tm, "Keep terse?")
	tm.Send(tea.KeyPressMsg{Code: 'x', Text: "x"})
	tm.Send(tea.KeyPressMsg{Code: tea.KeyTab})
	tm.Send(programEnter)
	waitForText(t, tm, "needs a prompt to replace the base with")
	frame := finalFrame(t, tm)

	def, err := config.LoadAgentFile(critic)
	if err != nil || !def.Current() || def.Mode != "read-only" || !def.Reviews || def.MaxRounds != 30 || def.Reasoning != "xhigh" {
		t.Fatalf("the saved critic = %+v, %v", def, err)
	}
	if got, _ := os.ReadFile(critic); !strings.HasPrefix(string(got), "# critic — argues against a diff; kept read-only on purpose\n") {
		t.Fatalf("the comment header was not kept:\n%s", got)
	}
	if got, _ := os.ReadFile(terse); string(got) != terseFile {
		t.Fatalf("a refused save touched the file:\n%s", got)
	}
	mu.Lock()
	defer mu.Unlock()
	if len(reloaded) != 1 || reloaded[0] != critic {
		t.Fatalf("the save should register the file again, reloaded %v", reloaded)
	}
	if !strings.Contains(frame, "Keep terse?") {
		t.Fatalf("the refused draft should stay on the card:\n%s", frame)
	}
	for _, role := range roles() {
		if role.Name == "critic" && role.Older {
			t.Fatal("the migrated critic is still in the older shape")
		}
	}
}
