package chat

// The route, run through the real program.
//
// A golden renders one surface in-process and proves what it looks like. This
// file asks the other question a golden cannot: does the key get there. It
// starts a real tea.Program over the session model, sends the keys a reader
// sends, lets the scripted provider's stream arrive on the runtime's own
// goroutines, and reads the frame the program ends on.
//
// On program-level goldens: there are none here, and none are wanted.
// teatest.RequireEqualOutput would capture the accumulated byte stream of
// every frame the renderer emitted — cursor moves, partial repaints and all —
// which is a record of how the runtime got to a screen rather than of the
// screen. internal/ui/golden already owns the screen, at four widths in two
// palettes, from a model built directly; a second golden of the same surface
// taken through the runtime would fail on a bubbletea repaint change that
// altered nothing anyone sees, and would have to be regenerated by whoever
// hit it, which is how a golden stops being read. So the assertions here name
// the text the route had to carry and nothing else, and the render stays the
// goldens' question.

import (
	"bytes"
	"context"
	"strings"
	"sync"
	"testing"
	"time"

	tea "charm.land/bubbletea/v2"
	"github.com/charmbracelet/x/exp/teatest/v2"
	"github.com/rfizzle/shhh/internal/provider"
)

// programTurn is one answer the provider gives, in the order the turns are
// listed: some text, some tool calls, or both.
type programTurn struct {
	text  string
	calls []provider.ToolCall
	// hold, when set, keeps this turn's events off the channel until it is
	// closed. It is what makes a card's arrival orderable against the keys
	// the test is sending: a decision that lands while the draft holds a
	// sentence arrives ungated, and a test that cannot say when it lands
	// cannot say which of the two branches it is testing (interrupt.go).
	hold chan struct{}
}

// programProvider is a provider.Provider that answers each request with the
// next scripted turn, repeating the last one once they run out — the same
// contract the driven scenes' fake endpoint has.
type programProvider struct {
	mu    sync.Mutex
	turns []programTurn
	next  int
}

func (p *programProvider) Name() string { return "scripted" }

func (p *programProvider) StreamCompletion(ctx context.Context, _ []provider.Message, _ provider.CompletionOpts) (<-chan provider.StreamEvent, error) {
	p.mu.Lock()
	turn := p.turns[min(p.next, len(p.turns)-1)]
	p.next++
	p.mu.Unlock()

	ch := make(chan provider.StreamEvent, 2)
	go func() {
		defer close(ch)
		if turn.hold != nil {
			select {
			case <-turn.hold:
			case <-ctx.Done():
				return
			}
		}
		if turn.text != "" {
			ch <- provider.StreamEvent{Token: turn.text}
		}
		ch <- provider.StreamEvent{ToolCalls: turn.calls, Done: true}
	}()
	return ch, nil
}

// streamOf is the adapter every host writes around its provider to hand the
// session a StreamFunc: a cancellable request per turn.
func streamOf(p provider.Provider) StreamFunc {
	return func(msgs []provider.Message, choice string) (<-chan provider.StreamEvent, context.CancelFunc, error) {
		ctx, cancel := context.WithCancel(context.Background())
		events, err := p.StreamCompletion(ctx, msgs, provider.CompletionOpts{ToolChoice: choice})
		if err != nil {
			cancel()
			return nil, nil, err
		}
		return events, cancel, nil
	}
}

// runProgram starts the session under a real tea.Program at a stated size.
// The size is sent as the WindowSizeMsg the program's first frame needs; the
// model draws nothing until it has one (model_test.go).
func runProgram(t *testing.T, m Model) *teatest.TestModel {
	t.Helper()
	tm := teatest.NewTestModel(t, m, teatest.WithInitialTermSize(120, 40))
	t.Cleanup(func() { _ = tm.Quit() })
	return tm
}

// waitForText blocks until the program has drawn s, and says what it was
// waiting for when it never does. The wait is on the frames rather than on a
// clock: a sleep is a guess about a machine's speed, and this suite runs on
// three of them.
//
// What it can wait for is a phrase the renderer wrote in one go — a row that
// appeared, a reply that arrived. It is reading the output stream, which is
// the terminal's repaints and not a screen, so a phrase that grew a
// character at a time is in there split across repaints and will never match.
// That is why the draft below is pasted rather than typed.
func waitForText(t *testing.T, tm *teatest.TestModel, s string) {
	t.Helper()
	teatest.WaitFor(t, tm.Output(), func(b []byte) bool {
		return bytes.Contains(b, []byte(s))
	}, teatest.WithDuration(10*time.Second), teatest.WithCheckInterval(10*time.Millisecond))
}

// finalFrame quits the program and returns the screen it ended on, stripped
// of colour. It is the model's own last View rather than the accumulated
// output, because the output is every frame the renderer emitted and the
// question here is what the last one said.
func finalFrame(t *testing.T, tm *teatest.TestModel) string {
	t.Helper()
	if err := tm.Quit(); err != nil {
		t.Fatalf("quitting the program: %v", err)
	}
	final, ok := tm.FinalModel(t, teatest.WithFinalTimeout(10*time.Second)).(Model)
	if !ok {
		t.Fatal("the program did not end on the chat model")
	}
	return stripANSI(final.View().Content)
}

// The keys a reader presses, spelled once: send, the handover that gives a
// waiting decision the keyboard, and the card's allow.
var (
	programEnter    = tea.KeyPressMsg{Code: tea.KeyEnter}
	programHandover = tea.KeyPressMsg{Code: tea.KeySpace, Mod: tea.ModCtrl}
	programAllow    = tea.KeyPressMsg{Code: 'y', Text: "y"}
)

// draftSentence is the half-typed line the card lands on top of.
const draftSentence = "half a thought"

// A typed line reaches the provider and the reply reaches the screen: the
// whole round trip through the runtime, with nothing driving Update by hand.
func TestProgram_ATypedLineFetchesAReplyOntoTheFrame(t *testing.T) {
	p := &programProvider{turns: []programTurn{{text: "the scripted answer"}}}
	tm := runProgram(t, New([]provider.Message{{Role: provider.RoleSystem, Content: "sys"}}, streamOf(p)))

	tm.Type("say something")
	tm.Send(programEnter)
	waitForText(t, tm, "the scripted answer")

	if frame := finalFrame(t, tm); !strings.Contains(frame, "the scripted answer") {
		t.Fatalf("the reply is not on the final frame:\n%s", frame)
	}
}

// heldCommandProgram is the fixture the two card tests share: a session whose
// next turn asks to run a command, held until the test says so, with a
// sentence in the draft when it lands. The sentence is what puts the card in
// its arrival state — on screen, keys not live, the draft still holding the
// keyboard — which is the state both keys below are asked about.
func heldCommandProgram(t *testing.T, ran *[]string) *teatest.TestModel {
	t.Helper()
	hold := make(chan struct{})
	// Released once, whichever way the test leaves: a fixture that fails
	// before the release would otherwise park the provider's goroutine on a
	// channel nothing will ever close.
	release := sync.OnceFunc(func() { close(hold) })
	t.Cleanup(release)
	p := &programProvider{turns: []programTurn{
		{hold: hold, calls: []provider.ToolCall{
			{ID: "call_1", Name: "execute_command", Arguments: `{"command":"echo hi"}`},
		}},
		{text: "and that is done"},
	}}
	m := New([]provider.Message{{Role: provider.RoleSystem, Content: "sys"}}, streamOf(p)).
		WithRunner(func(_ context.Context, cmd string) (string, int) {
			*ran = append(*ran, cmd)
			return "hi", 0
		})
	tm := runProgram(t, m)

	tm.Type("run it")
	tm.Send(programEnter)
	// Sent after the enter and therefore handled after it, so a frame
	// carrying this sentence is a frame where the turn is away and the draft
	// is not empty. It arrives as a paste because that lands in one repaint
	// and can be waited for; typed, it would be spread over as many repaints
	// as the renderer felt like.
	tm.Send(tea.PasteMsg{Content: draftSentence})
	waitForText(t, tm, draftSentence)

	release()
	waitForText(t, tm, "Assistant wants to run: echo hi")
	return tm
}

// The approval card is reachable by key, not only by render: the call
// arrives, the handover gives the card the keyboard, and [y] runs the
// command and puts its row in the transcript.
func TestProgram_TheApprovalCardsKeysRunTheCommand(t *testing.T) {
	var ran []string
	tm := heldCommandProgram(t, &ran)

	tm.Send(programHandover)
	tm.Send(programAllow)
	waitForText(t, tm, "and that is done")

	frame := finalFrame(t, tm)
	if len(ran) != 1 || ran[0] != "echo hi" {
		t.Fatalf("the allowed command did not reach the runner, got %v\n%s", ran, frame)
	}
	// The row the run left, read off the frame rather than off the model: the
	// act, what it was aimed at, and how it went.
	for _, want := range []string{"$ run", "echo hi", "ok ·"} {
		if !strings.Contains(frame, want) {
			t.Fatalf("the command's row is not in the transcript, no %q:\n%s", want, frame)
		}
	}
	if strings.Contains(frame, "Assistant wants to run") {
		t.Fatalf("the answered card is still on the screen:\n%s", frame)
	}
	// Answering hands the keyboard back at the character it was taken from.
	if !strings.Contains(frame, draftSentence) {
		t.Fatalf("the interrupted sentence did not come back:\n%s", frame)
	}
}

// The other half of invariant 5, asked of the whole program: while the draft
// holds the keyboard, the card's own answer key is a letter. It goes into the
// sentence, nothing runs, and the card is still waiting on the final frame
// (docs/interface/principles.md#a-key-is-inert-until-its-surface-holds-the-keyboard).
func TestProgram_ACardsKeyIsInertUntilTheHandover(t *testing.T) {
	var ran []string
	tm := heldCommandProgram(t, &ran)

	tm.Send(programAllow)
	// No wait: the quit inside finalFrame goes down the same queue as the
	// key, so the model it ends on is the model that has answered it.
	frame := finalFrame(t, tm)
	if !strings.Contains(frame, draftSentence+"y") {
		t.Fatalf("the card's key did not go into the sentence it landed on:\n%s", frame)
	}
	if len(ran) != 0 {
		t.Fatalf("a key the card does not hold ran the command: %v\n%s", ran, frame)
	}
	if !strings.Contains(frame, "Assistant wants to run: echo hi") {
		t.Fatalf("the card left the screen without being answered:\n%s", frame)
	}
	// And it says so rather than leaving the reader to infer it from a dim
	// key row (invariant 1).
	if !strings.Contains(frame, "not live yet") {
		t.Fatalf("the card does not say its keys are not live:\n%s", frame)
	}
}
