// Package design holds the tests that drive the design book's script. The
// book is built from the goldens and the scenes by book.py; there is no Go
// in it, so the tests run the script as a person does, with python3 -I, into
// a temporary directory.
package design

import (
	"bytes"
	"os"
	"os/exec"
	"path/filepath"
	"regexp"
	"strings"
	"testing"
)

// runBook runs book.py with the given arguments and standard input.
func runBook(t *testing.T, stdin string, args ...string) string {
	t.Helper()
	py, err := exec.LookPath("python3")
	if err != nil {
		t.Skip("python3 is not installed")
	}
	script, err := filepath.Abs("book.py")
	if err != nil {
		t.Fatal(err)
	}
	cmd := exec.Command(py, append([]string{"-I", script}, args...)...)
	cmd.Stdin = strings.NewReader(stdin)
	var out, errb bytes.Buffer
	cmd.Stdout, cmd.Stderr = &out, &errb
	if err := cmd.Run(); err != nil {
		t.Fatalf("book.py %v: %v\n%s", args, err, errb.String())
	}
	return out.String()
}

func read(t *testing.T, parts ...string) string {
	t.Helper()
	b, err := os.ReadFile(filepath.Join(parts...))
	if err != nil {
		t.Fatal(err)
	}
	return string(b)
}

func write(t *testing.T, content string, parts ...string) {
	t.Helper()
	p := filepath.Join(parts...)
	if err := os.MkdirAll(filepath.Dir(p), 0o755); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(p, []byte(content), 0o644); err != nil {
		t.Fatal(err)
	}
}

// goldenFixture writes one golden's colour render at 110 columns and its mono
// twin, in the shape internal/ui/golden writes them: a header, the layout
// block, then the ansi block with ESC written as a symbol.
func goldenFixture(t *testing.T, dir, name, label string) {
	t.Helper()
	for _, mono := range []string{"", ".mono"} {
		file := "# golden:  " + name + ".w110\n# surface: a fixture\n# width:   110 columns\n# palette: color\n# cursor:  none\n#\n" +
			"# Generated by the golden helper; do not edit by hand.\n\n" +
			"── layout ──────────────────────────────────────────────────\n" +
			"· " + label + "\nhello\n\n" +
			"── ansi ────────────────────────────────────────────────────\n" +
			"· " + label + "\n␛[38;5;214mhello␛[m\n"
		write(t, file, dir, name+".w110"+mono+".txt")
	}
}

func TestDesignBook_EveryGoldenHasAPage(t *testing.T) {
	root, err := filepath.Abs("../..")
	if err != nil {
		t.Fatal(err)
	}
	out := t.TempDir()
	runBook(t, "", "--root", root, "--out", out)

	file := regexp.MustCompile(`^(.+)\.w\d+(\.mono)?\.txt$`)
	want := map[string]bool{}
	for _, d := range []string{"internal/ui/chat/testdata/golden", "internal/ui/components/testdata/golden", "internal/ui/testdata/golden"} {
		entries, err := os.ReadDir(filepath.Join(root, d))
		if err != nil {
			t.Fatal(err)
		}
		for _, e := range entries {
			if m := file.FindStringSubmatch(e.Name()); m != nil {
				want[d+"/"+m[1]] = true
			}
		}
	}
	pages, err := filepath.Glob(filepath.Join(out, "surfaces", "*.html"))
	if err != nil {
		t.Fatal(err)
	}
	if len(pages) != len(want) {
		t.Fatalf("the book has %d surface pages for %d goldens", len(pages), len(want))
	}
	// One golden read by hand: the 110-column colour render comes first and
	// carries colour, and the other widths and the mono render follow.
	page := read(t, out, "surfaces", "agent-rows.html")
	at := func(s string) int { return strings.Index(page, s) }
	if at("<h3>110 columns") < 0 || at("<h3>110 columns") >= at("<h3>60 columns") || at("<h3>60 columns") >= at("<h3>130 columns") {
		t.Errorf("the widths are not in reading order: 110 %d, 60 %d, 130 %d", at("<h3>110 columns"), at("<h3>60 columns"), at("<h3>130 columns"))
	}
	if !strings.Contains(page, "<span class=f214>") || !strings.Contains(page, `<div class="mono">`) {
		t.Error("the page lacks its colour spans or its mono render")
	}
	if !strings.Contains(page, "<h4>four children working") {
		t.Error("the page lacks the panel label the golden gave")
	}
	if !strings.Contains(read(t, out, "index.html"), "surfaces/agent-rows.html") {
		t.Error("the index does not link the page")
	}
}

func TestDesignBook_AnsiBecomesSpans(t *testing.T) {
	for _, c := range []struct {
		name, in string
		want     []string
		not      []string
	}{
		{"plain", "a < b & c\nnext", []string{"a &lt; b &amp; c\nnext"}, []string{"<span"}},
		{"16 colour", "\x1b[31mred\x1b[0m and \x1b[1;92mbright\x1b[m", []string{"<span class=f1>red</span> and ", `class="f10 b"`, ">bright</span>"}, nil},
		{"256 colour", "\x1b[38;5;214mamber\x1b[0m \x1b[48;5;236mon grey \x1b[m␛[38;5;241mgolden form␛[m", []string{"<span class=f214>amber</span>", "<span class=g236>on grey </span>", "<span class=f241>golden form</span>"}, nil},
	} {
		t.Run(c.name, func(t *testing.T) {
			got := runBook(t, c.in, "--ansi")
			for _, w := range c.want {
				if !strings.Contains(got, w) {
					t.Errorf("missing %q in %q", w, got)
				}
			}
			for _, n := range c.not {
				if strings.Contains(got, n) {
					t.Errorf("unexpected %q in %q", n, got)
				}
			}
			if strings.Contains(got, "\x1b") || strings.Contains(got, "␛") {
				t.Errorf("an escape survived: %q", got)
			}
		})
	}
}

func TestDesignBook_TheIndexListsUnmappedGoldens(t *testing.T) {
	root, out := t.TempDir(), t.TempDir()
	write(t, "# Surfaces\n\n## Panels\n\n### Reading mode\n\nThe words about reading.\n\n### The input frame\n\nThe words about the frame.\n", root, "docs/interface/surfaces.md")
	dir := filepath.Join(root, "internal/ui/chat/testdata/golden")
	goldenFixture(t, dir, "reading-mode-search", "found") // matched by the heading's words
	goldenFixture(t, dir, "prompt-frame", "frame")        // matched by the explicit map
	goldenFixture(t, dir, "nothing-says-this", "orphan")  // matched by neither
	runBook(t, "", "--root", root, "--out", out)

	index := read(t, out, "index.html")
	cut := strings.Index(index, "no words yet")
	if cut < 0 {
		t.Fatal("the index has no \"no words yet\" list")
	}
	before, after := index[:cut], index[cut:]
	if !strings.Contains(after, "surfaces/nothing-says-this.html") {
		t.Error("the golden with no section is not listed under \"no words yet\"")
	}
	for _, name := range []string{"reading-mode-search", "prompt-frame"} {
		if !strings.Contains(before, "surfaces/"+name+".html") || strings.Contains(after, "surfaces/"+name+".html") {
			t.Errorf("%s should stand under its section and not under \"no words yet\"", name)
		}
	}
	if strings.Index(before, "Reading mode") > strings.Index(before, "The input frame") {
		t.Error("the sections are not in surfaces.md heading order")
	}
	if !strings.Contains(read(t, out, "surfaces", "nothing-says-this.html"), "No words yet") {
		t.Error("the unmapped page does not say it has no words")
	}
	if !strings.Contains(read(t, out, "words", "reading-mode.html"), "The words about reading.") {
		t.Error("the mapped section's words are not in the book")
	}
}

func TestDesignBook_AScenePageFollowsItsSteps(t *testing.T) {
	root, out := t.TempDir(), t.TempDir()
	steps := "# A fixture scene.\n# It has two snaps.\nsetup printf 'x'\nsnap 01-start \"Some things\"\nkeys Enter\n" +
		"# the card answers\nwide 120 snap 02-card \"[y] run it\" \"make check\" \"exit 2\"\nkeys y\n"
	write(t, steps, root, "scripts/tui/scenes/demo/steps.txt")
	write(t, "\x1b[38;5;214mSome things\x1b[m\n", root, "bin/tui/demo/01-start.ansi")
	write(t, "bare text only\n", root, "bin/tui/demo/02-card.txt")
	write(t, "snap 01-only \"words\"\n", root, "scripts/tui/scenes/bare/steps.txt")
	runBook(t, "", "--root", root, "--out", out)

	page := read(t, out, "scenes", "demo.html")
	order := []string{"A fixture scene.", "setup printf", "<h3>01-start</h3>", "<span class=f214>Some things</span>", "keys Enter",
		"<h3>02-card · only at 120 columns or wider</h3>", "<code>[y] run it</code>", "<code>make check</code>", "<code>exit 2</code>", "bare text only", "keys y"}
	last := -1
	for _, s := range order {
		at := strings.Index(page, s)
		if at < 0 || at < last {
			t.Fatalf("%q is missing or out of order in the scene page (at %d, after %d)", s, at, last)
		}
		last = at
	}
	bare := read(t, out, "scenes", "bare.html")
	if !strings.Contains(bare, "<code>words</code>") || !strings.Contains(bare, "no capture yet") {
		t.Errorf("a scene without captures should show its steps alone: %s", bare)
	}
	if index := read(t, out, "index.html"); !strings.Contains(index, "scenes/demo.html") || !strings.Contains(index, "scenes/bare.html") {
		t.Error("the index does not list the scenes")
	}
}
