package quality

import (
	"context"
	"os"
	"path/filepath"
	"reflect"
	"strings"
	"testing"
)

// genConfig is a config whose one generator appends the package each run was
// asked for to ran.txt, or fails where script says to.
func genConfig(script string) string {
	return `{"suites": {"default": {"checks": [{"name": "x", "exe": "true"}]}},
	"generated": [{"name": "goldens", "paths": ["internal/ui/**/testdata/golden/**"], "exe": "sh", "args": ["-c", "` + script + `"]}]}`
}

func TestLoadConfig_Generated(t *testing.T) {
	ws := t.TempDir()
	writeConfig(t, ws, genConfig("true"))
	cfg, err := LoadConfig(ws)
	if err != nil {
		t.Fatal(err)
	}
	if len(cfg.Generated) != 1 || cfg.Generated[0].Name != "goldens" {
		t.Fatalf("generated = %+v", cfg.Generated)
	}
	for _, bad := range []string{
		`{"suites": {"d": {"checks": [{"name": "x", "exe": "true"}]}}, "generated": [{"name": "g", "exe": "true"}]}`,
		`{"suites": {"d": {"checks": [{"name": "x", "exe": "true"}]}}, "generated": [{"name": "g", "paths": ["a/**"]}]}`,
		`{"suites": {"d": {"checks": [{"name": "x", "exe": "true"}]}}, "generated": [{"name": "g", "exe": "true", "paths": ["a/[x"]}]}`,
		`{"suites": {"d": {"checks": [{"name": "x", "exe": "true"}]}}, "generated": [{"name": "g", "exe": "true", "paths": ["a/**"], "typo": 1}]}`,
	} {
		writeConfig(t, ws, bad)
		if _, err := LoadConfig(ws); err == nil {
			t.Fatalf("expected a refusal for %s", bad)
		}
	}
}

// Only a declared path is generated: the rule is written down, never guessed.
func TestGenerated_MatchesOnlyTheDeclaredGlobs(t *testing.T) {
	ws := t.TempDir()
	writeConfig(t, ws, genConfig("true"))
	r := &Runner{Workspace: ws}
	got := r.Generated([]string{
		"internal/ui/chat/testdata/golden/a.w60.txt",
		"internal/ui/testdata/golden/b.txt",
		"internal/cli/testdata/golden/c.txt",
		"internal/ui/chat/model.go",
	})
	want := []string{"internal/ui/chat/testdata/golden/a.w60.txt", "internal/ui/testdata/golden/b.txt"}
	if !reflect.DeepEqual(got, want) {
		t.Fatalf("Generated = %v, want %v", got, want)
	}
	if got := (*Runner)(nil).Generated(want); got != nil {
		t.Fatalf("a nil runner — an untrusted checkout — declares nothing, got %v", got)
	}
	if got := (&Runner{Workspace: t.TempDir()}).Generated(want); got != nil {
		t.Fatalf("a workspace with no config declares nothing, got %v", got)
	}
}

// Each package a landing touched is regenerated once, in the tree it was
// pointed at, with its output kept as evidence.
func TestRegenerate_RunsOncePerPackageInTheGivenTree(t *testing.T) {
	ws := t.TempDir()
	writeConfig(t, ws, genConfig("echo {pkg} >> ran.txt"))
	dir := t.TempDir()
	var kept []string
	r := &Runner{Workspace: ws, Evidence: func(tool string, _ []byte) (string, error) {
		kept = append(kept, tool)
		return "ev-1", nil
	}}
	ran, err := r.Regenerate(context.Background(), dir, []string{
		"internal/ui/chat/testdata/golden/a.txt",
		"internal/ui/chat/testdata/golden/b.txt",
		"internal/ui/testdata/golden/c.txt",
		"README.md",
	})
	if err != nil {
		t.Fatal(err)
	}
	if len(ran) != 2 || !strings.Contains(ran[0], "./internal/ui/chat") || !strings.Contains(ran[1], "./internal/ui ") {
		t.Fatalf("ran = %q", ran)
	}
	data, _ := os.ReadFile(filepath.Join(dir, "ran.txt"))
	if string(data) != "./internal/ui/chat\n./internal/ui\n" {
		t.Fatalf("ran.txt = %q", data)
	}
	if _, err := os.Stat(filepath.Join(ws, "ran.txt")); err == nil {
		t.Fatal("the generator ran in the workspace rather than the tree it was given")
	}
	if len(kept) != 0 {
		t.Fatalf("output-free runs keep nothing, kept %v", kept)
	}
}

// A generator that fails says which one on its first line, names the kept
// output, and carries the output under it.
func TestRegenerate_AFailureNamesTheCommandAndItsOutput(t *testing.T) {
	ws := t.TempDir()
	writeConfig(t, ws, genConfig("echo boom; exit 3"))
	r := &Runner{Workspace: ws, Evidence: func(string, []byte) (string, error) { return "ev-7", nil }}
	_, err := r.Regenerate(context.Background(), t.TempDir(), []string{"internal/ui/testdata/golden/x.txt"})
	if err == nil {
		t.Fatal("a failing generator should be an error")
	}
	first, rest, _ := strings.Cut(err.Error(), "\n")
	if !strings.HasSuffix(first, "failed (exit 3); full output ev-7") || !strings.Contains(rest, "boom") {
		t.Fatalf("error = %q", err)
	}
}

// Every declared path in this repository is regenerated by a command, and
// its three rules resolve the way the landing will ask for them.
func TestThisRepositoryDeclaresItsGeneratedFiles(t *testing.T) {
	r := &Runner{Workspace: filepath.Join("..", "..")}
	cfg, err := LoadConfig(r.Workspace)
	if err != nil {
		t.Fatal(err)
	}
	gens, claimed := cfg.generations([]string{
		"internal/ui/components/testdata/golden/x.w60.txt",
		"docs/capabilities/configuration.md",
		"internal/cli/testdata/report/trust.txt",
		"docs/capabilities/subagents.md",
	})
	if len(claimed) != 3 {
		t.Fatalf("claimed = %v", claimed)
	}
	var lines []string
	for _, g := range gens {
		lines = append(lines, g.gen.Exe+" "+strings.Join(g.args, " "))
	}
	want := []string{
		"go test ./internal/ui/components -update-golden",
		"make docs",
		"go test ./internal/cli -update-golden",
	}
	if !reflect.DeepEqual(lines, want) {
		t.Fatalf("commands = %q, want %q", lines, want)
	}
}
